<a href="https://colab.research.google.com/github/GIT-REPO-JAGAN/PYTHON-GOOGLE-COLOB/blob/main/C_19Python_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Numerical Python
* Used for numerical/mathetical/scientific calculation in Python
* Data structures and functions for performing the calculations on numerical data

https://numpy.org/

In [3]:
import numpy as np

#### Numpy array - multi-dimentional array (N-d array)

In [8]:
l1 = [1, 2, 3, 4]   # List

In [3]:
type(l1)

list

In [11]:
arr1 = np.array(l1)  # List to Array

In [12]:
arr1

array([1, 2, 3, 4])

In [13]:
print(arr1)   # Arry prints in a way

[1 2 3 4]


In [14]:
type(arr1)

numpy.ndarray

In [15]:
arr1

array([1, 2, 3, 4])

In [16]:
arr1.ndim   # number of dimensions of a given array

1

In [17]:
arr1.dtype

dtype('int64')

In [18]:
print(arr1.dtype)

int64


In [19]:
help(int32)  # Its not in python so will not support

NameError: ignored

In [20]:
help(np.int32) # Its in Numpy so works

Help on class int32 in module numpy:

class int32(signedinteger)
 |  Signed integer type, compatible with C ``int``.
 |  
 |  :Character code: ``'i'``
 |  :Canonical name: `numpy.intc`
 |  :Alias on this platform (Linux x86_64): `numpy.int32`: 32-bit signed integer (``-2_147_483_648`` to ``2_147_483_647``).
 |  
 |  Method resolution order:
 |      int32
 |      signedinteger
 |      integer
 |      number
 |      generic
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __ge__(self, value, /)
 |      Return sel

In [21]:
help(np.int64)

Help on class int64 in module numpy:

class int64(signedinteger)
 |  Signed integer type, compatible with Python `int` and C ``long``.
 |  
 |  :Character code: ``'l'``
 |  :Canonical name: `numpy.int_`
 |  :Alias on this platform (Linux x86_64): `numpy.int64`: 64-bit signed integer (``-9_223_372_036_854_775_808`` to ``9_223_372_036_854_775_807``).
 |  :Alias on this platform (Linux x86_64): `numpy.intp`: Signed integer large enough to fit pointer, compatible with C ``intptr_t``.
 |  
 |  Method resolution order:
 |      int64
 |      signedinteger
 |      integer
 |      number
 |      generic
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return s

In [ ]:
help(np.int8)

Help on class int8 in module numpy:

class int8(signedinteger)
 |  Signed integer type, compatible with C ``char``.
 |  
 |  :Character code: ``'b'``
 |  :Canonical name: `numpy.byte`
 |  :Alias on this platform: `numpy.int8`: 8-bit signed integer (``-128`` to ``127``).
 |  
 |  Method resolution order:
 |      int8
 |      signedinteger
 |      integer
 |      number
 |      generic
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __gt__(self, value, /)
 |      Ret

In [ ]:
help(np.int16)

Help on class int16 in module numpy:

class int16(signedinteger)
 |  Signed integer type, compatible with C ``short``.
 |  
 |  :Character code: ``'h'``
 |  :Canonical name: `numpy.short`
 |  :Alias on this platform: `numpy.int16`: 16-bit signed integer (``-32_768`` to ``32_767``).
 |  
 |  Method resolution order:
 |      int16
 |      signedinteger
 |      integer
 |      number
 |      generic
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __gt__(self, value, /

In [22]:
arr1

array([1, 2, 3, 4])

In [23]:
arr1.size  # Counts all the elements

4

In [24]:
len(arr1)

4

In [25]:
l2 = [[1,2,3], [4,5,6]]  # 2 cross 3 array

In [26]:
arr2 = np.array(l2)

In [27]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [29]:
type(arr2)

numpy.ndarray

In [30]:
arr2.ndim # Total count of arrays

2

In [31]:
arr2.dtype

dtype('int64')

In [32]:
arr2.size  # Total count of elements

6

In [33]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
len(arr2)

2

In [35]:
arr2.shape   # It shows similar to 2 cross 3 array

(2, 3)

In [36]:
arr1

array([1, 2, 3, 4])

In [37]:
arr1.shape   # It shows only the size of the elements with ,

(4,)

In [38]:
a1 = np.array([[1,2,3], [5,6]])  # Not in a right format so it creats a like a list

<ipython-input-38-3aadeb1870ac>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a1 = np.array([[1,2,3], [5,6]])  # Not in a right format so it creats a like a list


In [39]:
a1

array([list([1, 2, 3]), list([5, 6])], dtype=object)

In [40]:
print(a1)

[list([1, 2, 3]) list([5, 6])]


In [41]:
type(a1)

numpy.ndarray

In [42]:
a1.ndim

1

In [43]:
a1.dtype

dtype('O')

In [44]:
arr3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [0,1,0]]])

In [45]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 0]]])

In [46]:
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 0]]]


In [47]:
arr3.dtype

dtype('int64')

In [48]:
arr3.ndim # easy way to find array number of dimensions just count array open's [[[

3

In [49]:
arr3.shape  # 2 main array, 2 inner array, 3 elements

(2, 2, 3)

In [50]:
arr3.size  # Total size of length

12

In [51]:
arr4 = np.array([[[[1,2,3]]]]) #count array open's [[[[  so dim= 4

In [52]:
arr4

array([[[[1, 2, 3]]]])

In [53]:
arr4.ndim

4

In [54]:
l1

[1, 2, 3, 4]

In [55]:
arr1

array([1, 2, 3, 4])

#### Check Add, Sub, Mul opperatcion in list & Array

In [56]:
l1 + 1   # Wil not work

TypeError: ignored

In [57]:
arr1 + 1  # Add 1 to all inner elements

array([2, 3, 4, 5])

In [46]:
arr1

array([1, 2, 3, 4])

In [58]:
arr1 + arr1

array([2, 4, 6, 8])

In [59]:
arr1 + arr1 + 1

array([3, 5, 7, 9])

In [60]:
out = []  # For loop is used in list to get out put what array do easy

for i in l1:
    out.append(i+1)

print(out)

[2, 3, 4, 5]


In [62]:
[i+1 for i in l1]   # One line For loop is used in list to get out put what array do easy

[2, 3, 4, 5]

In [63]:
arr1 + 1

array([2, 3, 4, 5])

In [64]:
%time [i+1 for i in l1]   # To calculate the timing of operaction

CPU times: user 7 µs, sys: 0 ns, total: 7 µs
Wall time: 11 µs


[2, 3, 4, 5]

In [65]:
%time arr1 + 1

CPU times: user 39 µs, sys: 6 µs, total: 45 µs
Wall time: 48.9 µs


array([2, 3, 4, 5])

In [66]:
a1 = np.arange(1, 100000)

In [67]:
a1

array([    1,     2,     3, ..., 99997, 99998, 99999])

In [68]:
range(1, 100000)

range(1, 100000)

In [69]:
%time a1 + 1

CPU times: user 252 µs, sys: 0 ns, total: 252 µs
Wall time: 264 µs


array([     2,      3,      4, ...,  99998,  99999, 100000])

In [70]:
%time [i+1 for i in range(1, 100000)]

CPU times: user 8.86 ms, sys: 3.06 ms, total: 11.9 ms
Wall time: 12 ms


[2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 1

In [74]:
l1

[1, 2, 3, 4]

In [78]:
arr1

array([1, 2, 3, 4])

In [72]:
arr1 + 1

array([2, 3, 4, 5])

In [75]:
l1 * 3   # In list it copys 3 times the same elemenet

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [77]:
arr1 * 3 # In Array it multiples 3 to each elemenet inside

array([ 3,  6,  9, 12])

In [80]:
l1 / 2

TypeError: ignored

In [79]:
arr1 / 2 # In Array it Divies 2 to each elemenet inside

array([0.5, 1. , 1.5, 2. ])

In [81]:
arr1

array([1, 2, 3, 4])

In [82]:
arr1 - 10

array([-9, -8, -7, -6])

In [83]:
arr1 == 1

array([ True, False, False, False])

In [84]:
arr1 % 2 == 0

array([False,  True, False,  True])

In [85]:
out = arr1 % 2 == 0

In [86]:
out

array([False,  True, False,  True])

In [87]:
out.dtype

dtype('bool')

In [88]:
out = arr1 / 2

In [89]:
out

array([0.5, 1. , 1.5, 2. ])

In [90]:
out.dtype

dtype('float64')

In [91]:
help(np.float64)

Help on class float64 in module numpy:

class float64(floating, builtins.float)
 |  float64(x=0, /)
 |  
 |  Double-precision floating-point number type, compatible with Python `float`
 |  and C ``double``.
 |  
 |  :Character code: ``'d'``
 |  :Canonical name: `numpy.double`
 |  :Alias: `numpy.float_`
 |  :Alias on this platform (Linux x86_64): `numpy.float64`: 64-bit precision floating-point number type: sign bit, 11 bits exponent, 52 bits mantissa.
 |  
 |  Method resolution order:
 |      float64
 |      floating
 |      inexact
 |      number
 |      generic
 |      builtins.float
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  

In [92]:
l1 = [1,2,'hi']

In [93]:
l1

[1, 2, 'hi']

In [94]:
l1 * 2

[1, 2, 'hi', 1, 2, 'hi']

In [95]:
a1 = np.array(l1)

In [96]:
a1   # Diffrent form of elements will not support

array(['1', '2', 'hi'], dtype='<U21')

In [98]:
a1.dtype

dtype('<U21')

#### Homogeneous type

In [99]:
l2 = [1,2,'5']  # Here it converts all other elements / values to string

In [100]:
a2 = np.array(l2)

In [101]:
a2

array(['1', '2', '5'], dtype='<U21')

In [102]:
a3 = np.array([10, 9.5, 'Python'])

In [104]:
a3

array(['10', '9.5', 'Python'], dtype='<U32')

In [105]:
a3.dtype

dtype('<U32')

In [106]:
a4 = np.array([10, 9.5, 'hi', [1,2]])

<ipython-input-106-23a627aa3344>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a4 = np.array([10, 9.5, 'hi', [1,2]])


In [107]:
a4

array([10, 9.5, 'hi', list([1, 2])], dtype=object)

In [108]:
a4.dtype

dtype('O')

In [109]:
a5 = np.array([10, 2.5, "We are learning NumPy using Python"])

In [110]:
a5

array(['10', '2.5', 'We are learning NumPy using Python'], dtype='<U34')

In [111]:
len('We are learning NumPy using Python')

34

In [124]:
a6 = np.array((1,2,3))
a6

array([1, 2, 3])

In [127]:
a1 = np.arange(10, 25, 1)   # 10 First elemenet, 15 Last element, 1 incremenet value
a1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

#### Random package

In [ ]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [130]:
np.random.randint(10, 25) # It just pick a random number between 10 to 25

19

In [132]:
np.random.randint(10, 25, (3, 4))  # It just pick a random number between 10 to 25 and create 3 cross 4 array

array([[14, 19, 22, 15],
       [17, 13, 15, 20],
       [20, 19, 12, 13]])

In [134]:
np.random.randint(10, 25, (3, 4))  # Every single run it creates new one

array([[20, 21, 18, 21],
       [17, 14, 22, 18],
       [13, 18, 15, 14]])

In [135]:
np.random.randint(10, 25, (3, 4))

array([[20, 23, 17, 16],
       [21, 14, 23, 11],
       [11, 22, 11, 12]])

In [136]:
np.random.randint(10, 25, (3, 2))

array([[22, 17],
       [22, 10],
       [12, 18]])

In [137]:
np.random.randint(0, 100, (3, 3))

array([[89, 57,  3],
       [ 0, 70, 44],
       [24, 11, 97]])

In [139]:
a1 = np.random.randint(0, 100, (3, 3))
a1

array([[94, 15, 89],
       [50, 83, 52],
       [18, 63, 25]])

In [ ]:
a1.dtype

dtype('int32')

In [ ]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [143]:
np.random.rand(2,3)  # will return a 2D array of shape (2, 3) filled with random numbers between 0 and 1

array([[0.89954254, 0.82814663, 0.93911675],
       [0.04930497, 0.30211086, 0.08160679]])

In [144]:
np.random.rand(5)

array([0.54683786, 0.56055227, 0.60620462, 0.38696312, 0.71430068])

In [ ]:
np.random.rand(5,4,2) #  will return a 3D array of shape (5, 4, 2) filled with random numbers between 0 and 1.

array([[[0.0565037 , 0.97744207],
        [0.50116712, 0.28907783],
        [0.76584126, 0.23810187],
        [0.01388797, 0.72034136]],

       [[0.55123062, 0.73629588],
        [0.47705548, 0.54651384],
        [0.93651869, 0.23959612],
        [0.50670624, 0.57790535]],

       [[0.6346146 , 0.88551627],
        [0.49721128, 0.25776002],
        [0.71336461, 0.33174659],
        [0.55513497, 0.95169136]],

       [[0.93780017, 0.01648406],
        [0.96694062, 0.21622835],
        [0.27001201, 0.40433707],
        [0.85750991, 0.98913103]],

       [[0.04258817, 0.73190909],
        [0.59316168, 0.54837015],
        [0.35092491, 0.69175952],
        [0.84027426, 0.222615  ]]])

#### zeros

In [ ]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [148]:
np.zeros((4,3))   # 4 Cross 3 array in default is float

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [149]:
z1 = np.zeros((4,3),dtype=int)  # 4 Cross 3 array make it to int
z1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [150]:
np.zeros((3,4),dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

#### ones

In [151]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [152]:
np.ones((4,2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [153]:
np.ones((4,2), dtype=bool)

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

#### full()

In [ ]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passe

In [154]:
np.full((2,3),5,dtype=int)  # everywere it filled full of 5

array([[5, 5, 5],
       [5, 5, 5]])

In [156]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [155]:
np.full((2,3),5.5)

array([[5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5]])

In [157]:
np.full((2,3),5.5,dtype=int)

array([[5, 5, 5],
       [5, 5, 5]])

#### Matrix functions

* Identity matrix??
* its a square matrix whose main diagonal elements are 1 and rest of the elements are 0s
* Square matrix => num of rows == num of cols

In [ ]:
help(np.identity)

Help on function identity in module numpy:

identity(n, dtype=None, *, like=None)
    Return the identity array.
    
    The identity array is a square array with ones on
    the main diagonal.
    
    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. note::
            The ``like`` keyword is an experimental feature pending on
            acceptance of :ref:`NEP 35 <NEP35>`.
    
        .. versionadded:: 1.20.0
    
    Returns
    -------
    out : ndarray
        `n` x `n` 

In [158]:
np.identity(3)   # here all (0,0) & (1,1) & (2,2) will be 1's

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [159]:
np.identity(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

#### eye

In [ ]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_functi

In [160]:
np.eye(4, 4, k=0, dtype=int)  # K=0 is equal to identity matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [161]:
np.eye(4, 4, k=1, dtype=int)  # K=1 is equal to the next value to identity matrix

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [ ]:
np.eye(4, 4, k=-1, dtype=int)  # K=-1 is equal to the next below value to identity matrix

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [ ]:
np.eye(4, 4, k=5, dtype=int)  # K=5 is equal to the identity matrix reason that is out of boundry

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.eye(4, 5, k=0, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [ ]:
np.eye(4, 5, k=1, dtype=int)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.eye(6, 4, k=1, dtype=int)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

#### **Diag** --> Get the respected dignal from the array / matrix


**Double click to open and see the ACTUAL FUNCTION**


    0   1   2
------------------
0|  1   2   3
1|  4   5   6
2|  7   8   9


(0,0) = 1
(0,1) = 2
(0,2) = 3

(1,0) = 4
(1,1) = 5
(1,2) = 6....



In [162]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [163]:
m1 = np.random.randint(10, 50, (4, 4))

In [165]:
m1

array([[44, 49, 35, 36],
       [32, 24, 49, 15],
       [44, 47, 45, 25],
       [32, 43, 19, 26]])

In [166]:
np.diag(m1) # 0th Dignal mean (0,0), (1,1), (2,2)...

array([44, 24, 45, 26])

In [167]:
np.diag(m1, k=1) # All 1th Dignal mean (0,1), (1,2), (2,2)...

array([49, 49, 25])

In [169]:
np.diag(m1, k=-1)

array([32, 47, 19])

In [171]:
np.diag(m1, k=-2)

array([44, 43])

In [172]:
np.diag(m1, k=-3)

array([32])

In [173]:
m1

array([[44, 49, 35, 36],
       [32, 24, 49, 15],
       [44, 47, 45, 25],
       [32, 43, 19, 26]])

In [174]:
np.diag(m1, k=-4)

array([], dtype=int64)

In [175]:
m1 = np.random.randint(10, 50, (4, 5))

In [176]:
m1

array([[37, 32, 26, 16, 42],
       [13, 13, 24, 16, 17],
       [11, 24, 47, 30, 37],
       [47, 31, 23, 43, 15]])

In [178]:
np.diag(m1, k=3)

array([16, 17])

In [179]:
a1

array([[94, 15, 89],
       [50, 83, 52],
       [18, 63, 25]])

In [180]:
arr1

array([1, 2, 3, 4])

In [181]:
np.diag(arr1)  # Make array one vale as a diagnal and form a matrix

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [182]:
np.diag(arr1, k=1)  # Add 0's at begining column

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [183]:
np.diag(arr1, k=2)  # Add 0's 2 time at begining column

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
help(np.diag)

Help on function diag in module numpy:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the flattened input 

In [184]:
a1

array([[94, 15, 89],
       [50, 83, 52],
       [18, 63, 25]])

In [185]:
list(a1)  # Make array as list

[array([94, 15, 89]), array([50, 83, 52]), array([18, 63, 25])]

In [186]:
arr1

array([1, 2, 3, 4])

In [187]:
list(arr1)

[1, 2, 3, 4]