<a href="https://colab.research.google.com/github/GIT-REPO-JAGAN/PYTHON-GOOGLE-COLOB/blob/main/C_20Python_NumPy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

#### fromfunction

In [2]:
np.fromfunction(lambda x, y: x + y, (3,3), dtype=int)  # The value at position (0, 0) is 0 + 0 = 0, the value at position (0, 1) is 0 + 1 = 1, and so on.

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
np.fromfunction(lambda x:x**2, (5,), dtype=int) # ,The lambda function x**2 is applied to each index x ranging from 0 to 4.

array([ 0,  1,  4,  9, 16], dtype=int32)

In [8]:
arr1 = np.random.randint(1, 20, (6,))

In [9]:
arr1

array([15, 15, 15,  1,  3, 18])

In [10]:
np.sum(arr1)

67

In [11]:
np.min(arr1)

1

In [12]:
np.max(arr1)

18

In [13]:
np.mean(arr1)  # mean = (addition of all elements) / 6

11.166666666666666

In [14]:
np.std(arr1)  # std = sqrt((sum((x - mean)^2) / N)

6.593346814950827

In [15]:
np.var(arr1) # var = sum((x - mean)^2) / N    -> N = 6

43.47222222222222

In [16]:
np.median(arr1)

15.0

In [17]:
arr2 = np.random.randint(1, 10, (3,4))

In [18]:
arr2

array([[3, 6, 8, 3],
       [7, 5, 3, 7],
       [8, 7, 7, 3]])

In [19]:
np.sum(arr2)

67

In [20]:
np.mean(arr2)   # Sorting the array in ascending order: [1,2,3,.... Taking the average of the two middle values: (V1 + V2) / 2 =

5.583333333333333

In [21]:
arr2

array([[3, 6, 8, 3],
       [7, 5, 3, 7],
       [8, 7, 7, 3]])

In [22]:
np.median(arr2)

6.5

In [5]:
a1 = np.random.randint(1, 10, (5,))
a2 = np.random.randint(1, 10, (5,))

In [24]:
a1

array([6, 6, 1, 5, 3])

In [25]:
a2

array([1, 1, 1, 4, 2])

In [26]:
a1 + a2

array([7, 7, 2, 9, 5])

In [27]:
a3 = np.random.randint(1, 10, (6,))

In [28]:
a1

array([6, 6, 1, 5, 3])

In [29]:
a3

array([1, 9, 9, 6, 7, 1])

In [30]:
a1 + a3

ValueError: ignored

In [31]:
a1

array([6, 6, 1, 5, 3])

In [32]:
a2

array([1, 1, 1, 4, 2])

In [33]:
a1 * a2

array([ 6,  6,  1, 20,  6])

In [34]:
a1 / a2

array([6.  , 6.  , 1.  , 1.25, 1.5 ])

In [35]:
a2/ a1

array([0.16666667, 0.16666667, 1.        , 0.8       , 0.66666667])

In [36]:
a1 - a2

array([5, 5, 0, 1, 1])

In [37]:
a1

array([6, 6, 1, 5, 3])

In [38]:
a2

array([1, 1, 1, 4, 2])

In [39]:
a1 > a2

array([ True,  True, False,  True,  True])

In [40]:
a1 and a2

ValueError: ignored

In [41]:
a4 = np.array([True, False, True])
a5 = np.array([True, True, False])

In [42]:
a4 and a5

ValueError: ignored

In [43]:
a4 & a5  # Same and operaction with & work

array([ True, False, False])

In [44]:
a4 | a5

array([ True,  True,  True])

In [45]:
a1

array([6, 6, 1, 5, 3])

In [46]:
a2

array([1, 1, 1, 4, 2])

In [47]:
a1 & a2

array([0, 0, 1, 4, 2])

In [48]:
a1

array([6, 6, 1, 5, 3])

In [49]:
a2

array([1, 1, 1, 4, 2])

In [50]:
np.add(a1, a2)

array([7, 7, 2, 9, 5])

In [51]:
np.subtract(a1, a2)

array([5, 5, 0, 1, 1])

In [52]:
np.divide(a1, a2)

array([6.  , 6.  , 1.  , 1.25, 1.5 ])

In [53]:
np.multiply(a1, a2)

array([ 6,  6,  1, 20,  6])

In [54]:
a1 ** a2

array([  6,   6,   1, 625,   9])

In [6]:
m1 = np.random.randint(1, 5, (2, 3))
m2 = np.random.randint(1, 5, (2, 3))

In [7]:
m1

array([[3, 2, 2],
       [3, 3, 1]])

In [57]:
m2

array([[2, 2, 4],
       [1, 4, 4]])

In [58]:
m1 + m2

array([[6, 4, 6],
       [2, 8, 7]])

In [59]:
np.add(m1, m2)

array([[6, 4, 6],
       [2, 8, 7]])

In [60]:
m1 - m2

array([[ 2,  0, -2],
       [ 0,  0, -1]])

In [61]:
m1 / m2

array([[2.  , 1.  , 0.5 ],
       [1.  , 1.  , 0.75]])

In [62]:
m3 = np.random.randint(1, 5, (3,3))

In [63]:
m3

array([[3, 2, 4],
       [1, 2, 3],
       [4, 1, 3]])

In [64]:
m1

array([[4, 2, 2],
       [1, 4, 3]])

In [65]:
m1 + m3

ValueError: ignored

In [66]:
m1

array([[4, 2, 2],
       [1, 4, 3]])

In [67]:
m2

array([[2, 2, 4],
       [1, 4, 4]])

In [68]:
m1 * m2

array([[ 8,  4,  8],
       [ 1, 16, 12]])

####**bold text** dot product

#### for dort product, the number of columns of the first matrix should be equal to number of rows of the second matrix

<----------> ROWS

* m1 => (r1, c1)
* m2 => (r2, c2)

* for dot product, c1 == r2
* and the shape of the outpt will be (r1, c2)

In [69]:
np.dot(m1, m2)

ValueError: ignored

In [70]:
m4 = np.array([
    [2,1,3],
    [4,0,1]
])

In [71]:
m5 = np.array([
    [1,4,1],
    [2,3,1],
    [0,1,2]
])

In [73]:
np.dot(m4, m5)

array([[ 4, 14,  9],
       [ 4, 17,  6]])

In [74]:
m4 @ m5   # @ symbol for dot multiplication

array([[ 4, 14,  9],
       [ 4, 17,  6]])

In [78]:
m1

array([[4, 2, 2],
       [1, 4, 3]])

In [79]:
m2

array([[2, 2, 4],
       [1, 4, 4]])

In [77]:
m1 > m2

array([[ True, False, False],
       [False, False, False]])

#### Indexing and Slicing of arrays

In [84]:
a1 = np.random.randint(1, 10, (10, ))

In [85]:
a1

array([2, 6, 1, 1, 8, 1, 6, 3, 8, 6])

In [86]:
a1[0]

2

In [87]:
a1[-1]

6

In [88]:
a1[0] = -1

In [89]:
a1

array([-1,  6,  1,  1,  8,  1,  6,  3,  8,  6])

In [90]:
id(a1)

140621257052240

In [91]:
a1[-1] = 0

In [92]:
a1

array([-1,  6,  1,  1,  8,  1,  6,  3,  8,  0])

In [93]:
id(a1)   # Mutable

140621257052240

In [94]:
a1

array([-1,  6,  1,  1,  8,  1,  6,  3,  8,  0])

#### When we create a slice froom an array, it creates a view, not a different array

In [95]:
a1[3:8:1]

array([1, 8, 1, 6, 3])

In [96]:
a1[4:7]

array([8, 1, 6])

In [97]:
a1[4:7] = -5

In [98]:
a1

array([-1,  6,  1,  1, -5, -5, -5,  3,  8,  0])

In [99]:
a1[4:7] = 7, 0, 2

In [100]:
a1

array([-1,  6,  1,  1,  7,  0,  2,  3,  8,  0])

In [102]:
a1[4:7] = 8, 9

ValueError: ignored

In [101]:
a1[4:7] = 9, 8, 7, 6

ValueError: ignored

In [103]:
a1

array([-1,  6,  1,  1,  7,  0,  2,  3,  8,  0])

In [104]:
sliced_a1 = a1[4:7]

In [105]:
sliced_a1

array([7, 0, 2])

In [106]:
type(sliced_a1)

numpy.ndarray

In [107]:
sliced_a1[0] = 11

In [ ]:
sliced_a1

array([11,  0,  2])

In [108]:
a1

array([-1,  6,  1,  1, 11,  0,  2,  3,  8,  0])

In [109]:
l1 = [1,2,3,4,5]

In [110]:
s1 = l1[1:3]

In [111]:
s1

[2, 3]

In [112]:
s1[0] = 100

In [115]:
s1

[100, 3]

In [116]:
l1

[1, 2, 3, 4, 5]

In [117]:
id(a1)

140621257052240

In [118]:
id(sliced_a1)

140621283297968

In [119]:
a2 = np.random.randint(0, 10, (3, 4))

In [120]:
a2

array([[5, 3, 5, 2],
       [7, 8, 3, 2],
       [4, 9, 9, 7]])

In [121]:
a2[0] # 0th row

array([5, 3, 5, 2])

In [122]:
a2[1][1]

8

In [123]:
a2[2][2]

9

In [124]:
a2[3][1]

IndexError: ignored

In [126]:
a2

array([[5, 3, 5, 2],
       [7, 8, 3, 2],
       [4, 9, 9, 7]])

In [127]:
a2[1][2]

3

In [128]:
a2[1,2]

3

In [131]:
a2[1:] # from (1,0) till end

array([[7, 8, 3, 2],
       [4, 9, 9, 7]])

In [130]:
a2

array([[5, 3, 5, 2],
       [7, 8, 3, 2],
       [4, 9, 9, 7]])

In [132]:
a2[1:, 2:]

array([[3, 2],
       [9, 7]])

In [133]:
a2[1:, :2]

array([[7, 8],
       [4, 9]])

In [134]:
s2 = a2[1:, :2] # view

In [ ]:
s2

array([[2, 5],
       [3, 3]])

In [135]:
s2[0,1]

8

In [136]:
s2[0,1] = 10

In [137]:
s2

array([[ 7, 10],
       [ 4,  9]])

In [138]:
a2

array([[ 5,  3,  5,  2],
       [ 7, 10,  3,  2],
       [ 4,  9,  9,  7]])

In [139]:
s3 = a2[1:, :2].copy()

In [140]:
s3

array([[ 7, 10],
       [ 4,  9]])

In [141]:
s3[1,1] = 100

In [142]:
s3

array([[  7,  10],
       [  4, 100]])

In [143]:
a2

array([[ 5,  3,  5,  2],
       [ 7, 10,  3,  2],
       [ 4,  9,  9,  7]])

In [145]:
a2

array([[ 5,  3,  5,  2],
       [ 7, 10,  3,  2],
       [ 4,  9,  9,  7]])

In [146]:
a2[1,1][2,3]

IndexError: ignored

In [147]:
a2[1,1]

10

In [153]:
a2[1,1]:[2,3]    # Not a right format

#### np.linspace

In [ ]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [ ]:
np.linspace(1, 10)   # function creates an array with 50 evenly spaced numbers between the start and end points

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
np.linspace(1, 20, 10) # 10 evenly spaced numbers    eg 3.11-1 = 2.11   same like  5.22-3.11 = 2.11 and so on

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [157]:
np.geomspace(1, 20, 10)  # function divides the interval between the start and end points into equal logarithmic steps.

array([ 1.        ,  1.39495079,  1.94588772,  2.71441762,  3.78647901,
        5.2819519 ,  7.368063  , 10.27808533, 14.33742329, 20.        ])

In [158]:
1.39495079 / 1

1.39495079

In [159]:
 1.94588772 / 1.39495079

1.394950799662259

In [160]:
np.geomspace(1, 10, 12)

array([ 1.        ,  1.23284674,  1.51991108,  1.87381742,  2.3101297 ,
        2.84803587,  3.51119173,  4.32876128,  5.33669923,  6.57933225,
        8.11130831, 10.        ])

In [161]:
help(np.geomspace)

Help on function geomspace in module numpy:

geomspace(start, stop, num=50, endpoint=True, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale (a geometric progression).
    
    This is similar to `logspace`, but with endpoints specified directly.
    Each output sample is a constant multiple of the previous.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The final value of the sequence, unless `endpoint` is False.
        In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
 

#### reshaping arrays

In [162]:
a1

array([-1,  6,  1,  1, 11,  0,  2,  3,  8,  0])

In [163]:
a1.shape

(10,)

In [164]:
np.reshape(a1, (3,3))

ValueError: ignored

In [165]:
np.reshape(a1, (5,2))  # reshapes accordangly

array([[-1,  6],
       [ 1,  1],
       [11,  0],
       [ 2,  3],
       [ 8,  0]])

In [166]:
np.reshape(a1, (2,5))

array([[-1,  6,  1,  1, 11],
       [ 0,  2,  3,  8,  0]])

In [167]:
a1

array([-1,  6,  1,  1, 11,  0,  2,  3,  8,  0])

In [168]:
a2

array([[ 5,  3,  5,  2],
       [ 7, 10,  3,  2],
       [ 4,  9,  9,  7]])

In [169]:
a2.size

12

In [170]:
np.reshape(a2, (4,3))

array([[ 5,  3,  5],
       [ 2,  7, 10],
       [ 3,  2,  4],
       [ 9,  9,  7]])

In [171]:
np.reshape(a2, (2,2,3))

array([[[ 5,  3,  5],
        [ 2,  7, 10]],

       [[ 3,  2,  4],
        [ 9,  9,  7]]])

In [172]:
np.reshape(a2, (12,))

array([ 5,  3,  5,  2,  7, 10,  3,  2,  4,  9,  9,  7])

In [173]:
a2

array([[ 5,  3,  5,  2],
       [ 7, 10,  3,  2],
       [ 4,  9,  9,  7]])

In [174]:
a2.shape

(3, 4)

#### transpose

In [177]:
a2

array([[ 5,  3,  5,  2],
       [ 7, 10,  3,  2],
       [ 4,  9,  9,  7]])

In [175]:
a2.transpose()  # Changes row to colume / cloume to row mut be equal

array([[ 5,  7,  4],
       [ 3, 10,  9],
       [ 5,  3,  9],
       [ 2,  2,  7]])

In [176]:
a2.T

array([[ 5,  7,  4],
       [ 3, 10,  9],
       [ 5,  3,  9],
       [ 2,  2,  7]])

#### Concatenate Axis

In [178]:
m1

array([[4, 2, 2],
       [1, 4, 3]])

In [179]:
m2

array([[2, 2, 4],
       [1, 4, 4]])

In [ ]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', '

In [ ]:
m1

array([[4, 2, 2],
       [3, 3, 1]])

In [ ]:
m2

array([[1, 3, 3],
       [1, 3, 4]])

In [ ]:
np.concatenate((m1, m2), axis=0) # Colume should be equal

array([[4, 2, 2],
       [3, 3, 1],
       [1, 3, 3],
       [1, 3, 4]])

In [ ]:
np.concatenate((m1, m2), axis=1)  #Row should be equal

array([[4, 2, 2, 1, 3, 3],
       [3, 3, 1, 1, 3, 4]])

#### Stacking

In [8]:
m1 = np.random.randint(1, 5, (2, 3))
m2 = np.random.randint(1, 5, (2, 3))

In [9]:
m1

array([[3, 1, 4],
       [4, 3, 4]])

In [10]:
m2

array([[2, 3, 1],
       [3, 2, 4]])

In [11]:
np.stack((m1, m2), axis=0)

array([[[3, 1, 4],
        [4, 3, 4]],

       [[2, 3, 1],
        [3, 2, 4]]])

In [12]:
np.stack((m1, m2), axis=1)

array([[[3, 1, 4],
        [2, 3, 1]],

       [[4, 3, 4],
        [3, 2, 4]]])

#### Splitting   -->  Equal split only alowed

In [18]:
a1 = np.random.randint(1, 10, (10,))

In [19]:
a1

array([1, 5, 2, 4, 1, 4, 5, 4, 3, 9])

In [20]:
a1.size

10

In [21]:
np.split(a1, 2)

[array([1, 5, 2, 4, 1]), array([4, 5, 4, 3, 9])]

In [23]:
np.split(a1, 3)

ValueError: ignored

In [22]:
np.split(a1, 5)

[array([1, 5]), array([2, 4]), array([1, 4]), array([5, 4]), array([3, 9])]

#### array_split  -->  Un-equal split only alowed

In [25]:
a1 = np.random.randint(1, 10, (10,))

In [26]:
a1

array([5, 1, 1, 4, 4, 9, 9, 3, 1, 2])

In [27]:
np.array_split(a1, 3)

[array([5, 1, 1, 4]), array([4, 9, 9]), array([3, 1, 2])]

In [ ]:
help(np.array_split)

Help on function array_split in module numpy:

array_split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays.
    
    Please refer to the ``split`` documentation.  The only difference
    between these functions is that ``array_split`` allows
    `indices_or_sections` to be an integer that does *not* equally
    divide the axis. For an array of length l that should be split
    into n sections, it returns l % n sub-arrays of size l//n + 1
    and the rest of size l//n.
    
    See Also
    --------
    split : Split array into multiple sub-arrays of equal size.
    
    Examples
    --------
    >>> x = np.arange(8.0)
    >>> np.array_split(x, 3)
    [array([0.,  1.,  2.]), array([3.,  4.,  5.]), array([6.,  7.])]
    
    >>> x = np.arange(9)
    >>> np.array_split(x, 4)
    [array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]



In [28]:
a1

array([5, 1, 1, 4, 4, 9, 9, 3, 1, 2])

In [29]:
# l = 10, n = 3

# l % n sub-arrays of size l//n + 1
# 10 % 3 sub-arrays of size 10//3 + 1
# 1 sub-array of size 3 + 1 = 4

# and the rest of size l//n.
# 2 sub-arrays of size 10//3 = 3

In [30]:
np.array_split(a1, 3)

[array([5, 1, 1, 4]), array([4, 9, 9]), array([3, 1, 2])]

#### where

In [ ]:
help(np.where)

Help on function where in module numpy:

where(...)
    where(condition, [x, y])
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called when x and y

In [33]:
a1

array([5, 1, 1, 4, 4, 9, 9, 3, 1, 2])

In [34]:
np.where(a1 > 5, a1/2, a1+1)  # If a is greater than 5 divide 2 else add 1

array([6. , 2. , 2. , 5. , 5. , 4.5, 4.5, 4. , 2. , 3. ])

In [35]:
np.where(a1 > 5, a1, 0)

array([0, 0, 0, 0, 0, 9, 9, 0, 0, 0])

In [36]:
marks = np.array([89, 91, 71, 45, 55, 61, 78, 53])

In [ ]:
# Pass or Fail
# 'Pass' if marks >= 60, else 'Fail'

In [37]:
np.where(marks >= 60, 'Pass', 'Fail')

array(['Pass', 'Pass', 'Pass', 'Fail', 'Fail', 'Pass', 'Pass', 'Fail'],
      dtype='<U4')

In [38]:
marks

array([89, 91, 71, 45, 55, 61, 78, 53])

In [41]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [43]:
transposed_arr = np.transpose(arr)
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


#### select

In [3]:
marks = np.array([89, 91, 71, 45, 55, 61, 78, 53])

In [4]:
conditions = [marks>=90, marks>=80 & marks<90, marks>=70 & marks<80, marks>=60 & marks<70, marks<60]
choices = ['A', 'B', 'C', 'D', 'F']

ValueError: ignored

In [5]:
marks>=90

array([False,  True, False, False, False, False, False, False])

In [6]:
marks>=80 & marks<90   # issue is with 2 vale comprassion

ValueError: ignored

In [7]:
(marks>=80) & (marks<90) # Now works

array([ True, False, False, False, False, False, False, False])

In [8]:
conditions = [marks>=90, (marks>=80) & (marks<90), (marks>=70) & (marks<80), (marks>=60) & (marks<70), marks<60]
choices = ['A', 'B', 'C', 'D', 'F']

In [9]:
np.select(conditions, choices)

array(['B', 'A', 'C', 'F', 'F', 'D', 'C', 'F'], dtype='<U3')

In [10]:
marks

array([89, 91, 71, 45, 55, 61, 78, 53])

In [11]:
conditions = [marks>=90, (marks>=80) & (marks<90), (marks>=70) & (marks<80), (marks>=60) & (marks<70)]
choices = ['A', 'B', 'C', 'D']
default_grade = 'F'   # also we can add default value

In [12]:
np.select(conditions, choices, default_grade)

array(['B', 'A', 'C', 'F', 'F', 'D', 'C', 'F'], dtype='<U1')